<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Fuska</title>
        <link href="<?php echo $this->basePath ?>vendor/fontawesome/css/font-awesome.min.css?v=<?php echo $this->version ?>" rel="stylesheet" />
    </head>
    <body>
        <style>
            #toolbar .navbar {
                border-radius: 0;
                margin-bottom: 4px;
            }
        </style>
        <div id="cache" style="display: none;"><div class="html"></div></div>
        <div id="layout" style="position: absolute; top: 5px; left: 0; bottom: 5px; right: 0;"></div>
        <script>
            var basePath = "<?php echo $this->basePath ?>";
            var jsBasePath = "<?php echo $this->jsBasePath ?>";
            var theme = "<?php echo $this->theme ?>";
            var themePath = "<?php echo $this->themePath ?>";
            var env = "<?php echo $this->env ?>";
            var version = "<?php echo $this->version ?>";
        </script>
        <script data-main="<?php echo $this->jsBasePath ?>js/app.js?v=<?php echo $this->version ?>" src="<?php echo $this->basePath ?>vendor/requirejs/require.js"></script>
    </body>
</html>
