<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>RIA</title>
    </head>
    <body>
        <style>
            #toolbar .navbar {
                border-radius: 0;
                margin-bottom: 4px;
            }
        </style>
        <div id="toolbar">
            <nav class="navbar navbar-default" role="navigation">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <a class="navbar-brand" href="#">
                            <img alt="Br-Flow" src="...">
                        </a>
                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav">
                            <li><a class="link-ajax" href="admin/index/segunda-tela">Segunda Tela</a></li>
                            <li><a class="link-ajax" href="admin/index/terceira-tela">Terceira Tela</a></li>
                            <li><a class="link-ajax" data-target="left" href="admin/index/segunda-tela">Segunda Tela - Left</a></li>
                            <li><a class="link-ajax" data-target="left" href="admin/index/terceira-tela">Terceira Tela - Left</a></li>
                        </ul>
                    </div>
                </div>
            </nav>                    

        </div>
        <div id="layout" style="height: 400px"></div>
        <script>
            var basePath = "<?php echo $this->basePath ?>";
            var theme = "<?php echo $this->theme ?>";
            var themePath = "<?php echo $this->themePath ?>";
            var env = "<?php echo $this->env ?>";
        </script>
        <script data-main="public/js/app" src="<?php echo $this->basePath ?>vendor/requirejs/require.js"></script>
    </body>
</html>
