<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Fuska PHP</title>
    </head>
    <body>
        <div class="container">
            <div class="row">
                <?php //echo $this->content ?>
            </div>
        </div>

        <script src="<?php echo $this->basePath ?>js/bootstrap/jquery.min.js"></script>
    </body>
</html>
