<div data-block-target="main" id="grupo-usuarios-cadastro-main" class="container-fluid">
    <div class='form form-horizontal' style="width: 100%;">
        <div class="form-group">
            <label for="input-nome" class="col-sm-2 control-label">Nome</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" id="input-nome" name='nome' placeholder="Nome" />
            </div>
        </div>
        <div class="form-group">
            <label for="input-status" class="col-sm-2 control-label">Status</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" id="input-status" name='status' placeholder="Status" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <input type="button" name='salvar' class="btn btn-primary" value='Salvar' />
            </div>
        </div>
    </div>
</div>