<div data-block-target="main" id="usuario-cadastro-main" class="container-fluid">
    <div class='form form-horizontal' style="width: 100%;">
        <div class="form-group">
            <label for="input-login" class="col-sm-2 control-label">Login</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" id="input-login" name='login' placeholder="Login" />
            </div>
        </div>
        <div class="form-group">
            <label for="input-senha" class="col-sm-2 control-label">Senha</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" id="input-senha" name='senha' placeholder="Senha" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="button" name='salvar' class="btn btn-primary">Salvar</button>
            </div>
        </div>
    </div>
</div>