<div data-block-target="top" id="app-top" class="form-horizontal">
    <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand link-ajax" href="main/index/index">Fuska</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a class="link-ajax" href="main/index/index">Principal</a></li>
                    <li><a class="link-ajax" href="admin/index/index">Administração</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a class="layout-toggle-left" href="#">Mostrar/Esconder Menu</a></li>
                    <li><a class="system-logout" href="#">Sair</a></li>
                </ul>
            </div>
        </div>
    </nav>
</div>
<div data-block-target="left" id="app-left" class="form-horizontal" style="height: 100%; width: 100%;">

</div>
<div data-block-target="main" id="app-main" class="form-horizontal">
    Tela principal<br />
</div>